version: "3"
services:
  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "geo-database"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default
  web:
    image: geo-server
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "geo-database"
volumes:
  database-data: